name: asi_projekt
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas>=1.4.0
  - scikit-learn>=1.1.0
  - seaborn>=0.12.1
  - notebook
  - ipython>=8.10
  - jupyterlab>=3.0
  - pyarrow  # for Parquet support
  - pip:
      - kedro[jupyter]~=0.19.12
      - kedro-datasets[pandas-csvdataset, pandas-exceldataset, pandas-parquetdataset, spark-sparkdataset, plotly-plotlydataset, plotly-jsondataset, matplotlib-matplotlibwriter]>=3.0
      - kedro-viz>=6.7.0
      - imbalanced-learn>=0.10.0
      - streamlit
      - joblib
